In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("train.csv")

In [3]:
data.loc[0:10]

id  discourse_id  discourse_start  discourse_end  \
0   423A1CA112E2  1.622628e+12              8.0          229.0   
1   423A1CA112E2  1.622628e+12            230.0          312.0   
2   423A1CA112E2  1.622628e+12            313.0          401.0   
3   423A1CA112E2  1.622628e+12            402.0          758.0   
4   423A1CA112E2  1.622628e+12            759.0          886.0   
5   423A1CA112E2  1.622628e+12            887.0         1150.0   
6   423A1CA112E2  1.622628e+12           1151.0         1533.0   
7   423A1CA112E2  1.622628e+12           1534.0         1602.0   
8   423A1CA112E2  1.622628e+12           1603.0         1890.0   
9   423A1CA112E2  1.622628e+12           1891.0         2027.0   
10  A8445CABFECE  1.622576e+12             18.0           85.0   

                                       discourse_text        discourse_type  \
0   Modern humans today are always on their phone....                  Lead   
1   They are some really bad consequences when stu...              Position   
2   Some certain areas in the United States ban ph...              Evidence   
3   When people have phones, they know about certa...              Evidence   
4   Driving is one of the way how to get around. P...                 Claim   
5   That's why there's a thing that's called no te...              Evidence   
6   Sometimes on the news there is either an accid...              Evidence   
7   Phones are fine to use and it's also the best ...                 Claim   
8   If you go through a problem and you can't find...              Evidence   
9   The news always updated when people do somethi...  Concluding Statement   
10  Drivers should not be able to use phones while...              Position   

        discourse_type_num                                   predictionstring  
0                   Lead 1  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 1...  
1               Position 1       45 46 47 48 49 50 51 52 53 54 55 56 57 58 59  
2               Evidence 1    60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75  
3               Evidence 2  76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 9...  
4                  Claim 1  139 140 141 142 143 144 145 146 147 148 149 15...  
5               Evidence 3  163 164 165 166 167 168 169 170 171 172 173 17...  
6               Evidence 4  211 212 213 214 215 216 217 218 219 220 221 22...  
7                  Claim 2  282 283 284 285 286 287 288 289 290 291 292 29...  
8               Evidence 5  297 298 299 300 301 302 303 304 305 306 307 30...  
9   Concluding Statement 1  355 356 357 358 359 360 361 362 363 364 365 36...  
10              Position 1                       3 4 5 6 7 8 9 10 11 12 13 14

In [4]:
data.shape

(144293, 8)

In [5]:
pd.set_option('display.max_colwidth', None)
x = np.random.randint(0,[144293])[0]
print(data.iloc[x].id)
print()
print(data[data.id==data.loc[x].id][["discourse_text","discourse_type_num"]])
print("\n\n")
str(data.iloc[x].id)+'.txt'
with open('train/'+str(data.iloc[x].id)+'.txt') as f:
    lines = f.readlines()
    print(lines)

1FBC2049262E

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         discourse_text  \
7465                                                                                                                                                                           

## Following the tensorflow BERT tutorial

In [6]:


import os

import numpy as np
import matplotlib.pyplot as plt

import tensorflow as tf

import tensorflow_hub as hub

import tensorflow.keras as keras

import tensorflow_text as text

import bert

from transformers import TFBertModel, BertConfig, BertTokenizer

from tensorflow.keras import layers

from tokenizers import BertWordPieceTokenizer

2022-05-23 10:07:31.573572: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [7]:
max_len = 364
configuration = BertConfig(output_hidden_states=True)

## tutorial from keras.io text extraction with BERT


In [8]:
# Save the slow pretrained tokenizer
slow_tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
save_path = "bert_base_uncased/"
if not os.path.exists(save_path):
    os.makedirs(save_path)
slow_tokenizer.save_pretrained(save_path)

# Load the fast tokenizer from saved file
tokenizer = BertTokenizer("bert_base_uncased/vocab.txt", lowercase=True)

In [9]:
model = TFBertModel.from_pretrained("bert-base-uncased", config=configuration)

Some layers from the model checkpoint at bert-base-uncased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-uncased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [21]:
tokens = tokenizer.encode_plus("One. ", "One short sentence short.", " Hello friend.",  # maximum length of a sentence
    pad_to_max_length=True,  # Add [PAD]s
    return_attention_mask = True,  # Generate the attention mask
    return_tensors = 'tf'
                              )
print(tokens)

{'input_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=
array([[ 101, 2028, 1012,  102, 2028, 2460, 6251, 2460, 1012,  102]],
      dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[0, 0, 0, 0, 1, 1, 1, 1, 1, 1]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 10), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}


In [22]:
model(tokens).last_hidden_state

<tf.Tensor: shape=(1, 10, 768), dtype=float32, numpy=
array([[[-0.24667083, -0.03104116, -0.52856493, ..., -0.45312554,
          0.24253574,  0.3914031 ],
        [-0.12952062, -0.45887968, -0.6460501 , ...,  0.13332042,
          0.64121157,  0.19036917],
        [-0.63241535, -0.7423376 , -0.49782598, ...,  0.61106247,
          0.31030506, -0.5502998 ],
        ...,
        [ 0.10222562, -0.04072233, -0.14299254, ..., -0.08979049,
          0.06220614, -0.20934309],
        [ 0.7370381 , -0.04299054, -0.618948  , ...,  0.13325801,
         -0.31115365, -0.320015  ],
        [ 0.84929156, -0.0548588 , -0.6002508 , ...,  0.16416922,
         -0.34933597, -0.25471267]]], dtype=float32)>

<tf.Tensor: shape=(1, 12, 768), dtype=float32, numpy=
array([[[-0.11370594,  0.11691775, -0.10730496, ..., -0.3399709 ,
          0.2530314 ,  0.6903751 ],
        [-0.51107824, -0.08288598,  0.24628703, ..., -0.13993774,
          0.03633105,  0.894439  ],
        [-0.19683118, -0.20921662,  0.19922468, ..., -0.02733088,
          0.11338456,  1.0472364 ],
        ...,
        [ 0.60888886, -0.40845504,  0.10645159, ..., -0.7748293 ,
         -0.20368706, -0.04161462],
        [ 0.10792276, -0.7061552 , -0.71147954, ...,  0.37472823,
          0.5758974 ,  0.1508598 ],
        [ 0.7728993 ,  0.31993365,  0.03112878, ..., -0.04425373,
         -0.58441895, -0.39986992]]], dtype=float32)>

In [70]:
tokens

{'input_ids': <tf.Tensor: shape=(1, 12), dtype=int32, numpy=
array([[ 101, 2023, 2003, 1037, 2235, 6251, 1012, 2079, 2017, 2228, 1012,
         102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)>}

In [23]:
outputs = model(tokens)
print(len(outputs))  # 3

hidden_states = outputs[2]
print(len(hidden_states))  # 13

embedding_output = hidden_states[0]
attention_hidden_states = hidden_states[1:]

3
13


In [33]:
hidden_states[12]

<tf.Tensor: shape=(1, 10, 768), dtype=float32, numpy=
array([[[-0.24667083, -0.03104116, -0.52856493, ..., -0.45312554,
          0.24253574,  0.3914031 ],
        [-0.12952062, -0.45887968, -0.6460501 , ...,  0.13332042,
          0.64121157,  0.19036917],
        [-0.63241535, -0.7423376 , -0.49782598, ...,  0.61106247,
          0.31030506, -0.5502998 ],
        ...,
        [ 0.10222562, -0.04072233, -0.14299254, ..., -0.08979049,
          0.06220614, -0.20934309],
        [ 0.7370381 , -0.04299054, -0.618948  , ...,  0.13325801,
         -0.31115365, -0.320015  ],
        [ 0.84929156, -0.0548588 , -0.6002508 , ...,  0.16416922,
         -0.34933597, -0.25471267]]], dtype=float32)>